version: '3'

services:
  # ganachecli: simulated test rpc on dev environment
  ganache-cli:
    container_name: ganache-cli
    build:
      context: ./ganache
    ports:
      - 8546:8546

  # truffle-suite
  # volumes are used here to enable hot editing :) Nice trick!
  truffle-app:
    container_name: truffle-app
    build:
      context: ./
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' localhost:8546
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - 4001:4001
    tty: true
    volumes:
      - './:/app'
      - '/app/node_modules'